# Generated by Django 3.2.7 on 2021-09-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'running'), (2, 'stop'), (3, 'restart'), (4, '正在初始化中'), (5, '構建失敗')], default=4)),
                ('check', models.CharField(default='', max_length=64)),
                ('task', models.CharField(default='', max_length=64)),
                ('is_finish', models.BooleanField(default=False)),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vm.instance')),
            ],
        ),
    ]
