# Generated by Django 3.2.7 on 2021-09-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.SmallIntegerField(choices=[(1, '服務器'), (2, '網路設備')], default=1)),
                ('device_status_id', models.SmallIntegerField(choices=[(1, '上架'), (2, '線上'), (3, '離線'), (4, '下架')], default=1, verbose_name='狀態')),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField()),
                ('size', models.SmallIntegerField(default=1, verbose_name='機型大小(U)')),
                ('name', models.CharField(max_length=64, verbose_name='名稱')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='資產編號')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '資產',
                'verbose_name_plural': '資產表',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='機房')),
                ('floor', models.IntegerField(verbose_name='樓層')),
            ],
            options={
                'verbose_name_plural': '機房表',
            },
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('ip_range', models.CharField(max_length=64, verbose_name='IP範圍')),
                ('netmask', models.CharField(max_length=64, verbose_name='NETMASK')),
                ('geteway', models.CharField(max_length=64, verbose_name='GETEWAY')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': 'ISP',
                'verbose_name_plural': 'ISP',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.SmallIntegerField(choices=[(1, '路由器'), (2, '交換機'), (3, '防火牆')], default=2, verbose_name='設備類型')),
                ('name', models.CharField(max_length=64, verbose_name='設備名稱')),
                ('manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='管理IP')),
                ('intranet_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='內網IP')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='SN號')),
                ('manufactory', models.CharField(blank=True, max_length=128, null=True, verbose_name='製造商')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='型號')),
                ('port_num', models.SmallIntegerField(blank=True, null=True, verbose_name='端口個數')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('latest_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='保固日期')),
            ],
            options={
                'verbose_name': '網絡設備',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='機櫃號')),
                ('height', models.SmallIntegerField(default=42, verbose_name='高度')),
                ('max_power', models.PositiveSmallIntegerField(default=0, verbose_name='最大功率')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.idc', verbose_name='機房')),
                ('isp', models.ManyToManyField(to='asset.ISP', verbose_name='ISP')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='標籤')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name_plural': '標籤表',
            },
        ),
        migrations.CreateModel(
            name='RackUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Front'), (2, 'Back')], default=1, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.rack')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.rack', verbose_name='機櫃'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.tag', verbose_name='標籤'),
        ),
    ]
