# Generated by Django 3.2.7 on 2021-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrac',
            name='passwd',
            field=models.CharField(default='a2f559ce', max_length=64, verbose_name='密碼'),
        ),
    ]
